"""empty message

Revision ID: 79b70e6535d8
Revises: 
Create Date: 2020-01-01 13:02:03.817125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79b70e6535d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksi',
    sa.Column('id_transaksi', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_pembeli', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_penjual', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('waktu_pembelian', mysql.DATETIME(), nullable=True),
    sa.Column('waktu_konfirmasi', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['id_pembeli'], ['users.user_id'], name='transaksi_ibfk_1'),
    sa.ForeignKeyConstraint(['id_penjual'], ['users.user_id'], name='transaksi_ibfk_2'),
    sa.PrimaryKeyConstraint('id_transaksi'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
